name: Cypress Tests

on: workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:  
      run:
        working-directory: ./QA-Portfolio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test
        env:
          CI: true
